main: harrypotterplugin.main.HarryPotterPlugin
name: HarryPotterPlugin
version: '1.0'
author: Der_Zauberer
api-version: 1.14

commands:
  harrypotter:
    description: Open the inventory for items
    usage: /<command>
    permission: harrypotter.command.harrypotter
    aliases: [hp]

permissions:
  harrypotter.command.harrypotter:
    description: Open the inventory for items
    default: op